import {
  Award,
  Baby,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  CalendarDays,
  Check,
  CheckCheck,
  Clock,
  Compass,
  CreditCard,
  FileText,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  HeartHandshake,
  ImageIcon,
  Languages,
  Library,
  Lightbulb,
  Mail,
  MapPin,
  Medal,
  MessageSquare,
  Mic,
  Music,
  NotebookPen,
  PenLine,
  Percent,
  Phone,
  Play,
  Presentation,
  Puzzle,
  Rocket,
  School,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Video,
  Wallet,
  Zap,
  type LucideProps,
} from 'lucide-react';

/**
 * Curated icon set. Named imports (not `import * as`) keep the client bundle
 * small — a wildcard import would ship all 6,000 lucide icons to the browser.
 * The admin icon picker offers exactly these names.
 */
export const ICON_SET = {
  Award,
  Baby,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  CalendarDays,
  Check,
  CheckCheck,
  Clock,
  Compass,
  CreditCard,
  FileText,
  Flag,
  Gift,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  HeartHandshake,
  ImageIcon,
  Languages,
  Library,
  Lightbulb,
  Mail,
  MapPin,
  Medal,
  MessageSquare,
  Mic,
  Music,
  NotebookPen,
  PenLine,
  Percent,
  Phone,
  Play,
  Presentation,
  Puzzle,
  Rocket,
  School,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Target,
  ThumbsUp,
  Timer,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Video,
  Wallet,
  Zap,
} satisfies Record<string, React.ComponentType<LucideProps>>;

export type IconName = keyof typeof ICON_SET;

export const ICON_NAMES = Object.keys(ICON_SET) as IconName[];

/** Renders an icon by the name stored in the database; falls back to a sparkle. */
export function Icon({ name, className }: { name?: string | null; className?: string }) {
  const Component = (name && ICON_SET[name as IconName]) || Sparkles;
  return <Component className={className} aria-hidden />;
}
