import {
  Briefcase,
  ChartNoAxesColumn,
  ClipboardList,
  FileText,
  FolderTree,
  Gift,
  GraduationCap,
  Image,
  Inbox,
  LayoutDashboard,
  ListChecks,
  ListOrdered,
  Mail,
  MapPin,
  Menu,
  MessageCircleQuestion,
  Newspaper,
  Presentation,
  Puzzle,
  Quote,
  Rows3,
  ScrollText,
  Settings,
  Sparkles,
  Trophy,
  UserCog,
  Users,
  type LucideProps,
} from 'lucide-react';

/** Named imports only — see components/shared/icon.tsx for why. */
const ADMIN_ICONS = {
  Briefcase,
  ChartNoAxesColumn,
  ClipboardList,
  FileText,
  FolderTree,
  Gift,
  GraduationCap,
  Image,
  Inbox,
  LayoutDashboard,
  ListChecks,
  ListOrdered,
  Mail,
  MapPin,
  Menu,
  MessageCircleQuestion,
  Newspaper,
  Presentation,
  Puzzle,
  Quote,
  Rows3,
  ScrollText,
  Settings,
  Sparkles,
  Trophy,
  UserCog,
  Users,
} satisfies Record<string, React.ComponentType<LucideProps>>;

export function AdminIcon({ name, className }: { name: string; className?: string }) {
  const Component = ADMIN_ICONS[name as keyof typeof ADMIN_ICONS] ?? LayoutDashboard;
  return <Component className={className} aria-hidden />;
}
