import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Copies the web fonts into the repo and writes the `@font-face` rules that
 * serve them, so building the site needs no network.
 *
 * `next/font/google` downloads Inter and Poppins during `next build`. That is
 * fine locally and fatal in a Docker build on a slow link: two production
 * deploys failed on `Failed to fetch \`Inter\` from Google Fonts` and a socket
 * timeout, having already built everything else.
 *
 * Rather than hand-write the rules, this lifts exactly what `next/font`
 * generated — the same files, the same `unicode-range` splits so a page only
 * downloads the subsets its text needs, and the metric-adjusted fallback faces
 * that stop the swap from shifting layout. Rendering is unchanged; only the
 * source of the bytes moves.
 *
 * Run it after a build that still used `next/font/google` — that is what
 * populates `.next/static/media` — and commit the result:
 *
 *   pnpm build && node scripts/vendor-fonts.mjs
 */
const root = process.cwd();
const cssDir = path.join(root, '.next/static/css');
const mediaDir = path.join(root, '.next/static/media');
const outDir = path.join(root, 'public/fonts');
const outCss = path.join(root, 'src/app/fonts.css');

const FAMILIES = ['Inter', 'Poppins'];

let css = '';
for (const file of readdirSync(cssDir).filter((name) => name.endsWith('.css'))) {
  css += readFileSync(path.join(cssDir, file), 'utf8');
}

const faces = [...css.matchAll(/@font-face\{[^}]*\}/g)].map((match) => match[0]);
const wanted = faces.filter((face) =>
  FAMILIES.some((family) => face.includes(`font-family:${family}`)),
);

if (wanted.length === 0) {
  console.error('No @font-face rules found — run `pnpm build` with next/font first.');
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });

const copied = new Set();
const preload = [];

const rules = wanted.map((face) =>
  face.replace(/url\(\/_next\/static\/media\/([^)]+)\)/g, (_, filename) => {
    if (!copied.has(filename)) {
      copyFileSync(path.join(mediaDir, filename), path.join(outDir, filename));
      copied.add(filename);
      // `next/font` marks the subsets it preloads with `.p.` in the filename.
      if (filename.includes('.p.')) preload.push(filename);
    }
    return `url(/fonts/${filename})`;
  }),
);

// Deduplicate: the same face can appear in more than one chunk's stylesheet.
const unique = [...new Set(rules)];

const header = `/*
 * Generated by scripts/vendor-fonts.mjs — do not edit by hand.
 *
 * These are the rules \`next/font/google\` used to emit, with the files served
 * from /fonts instead of fetched from Google at build time. Keeping the
 * per-subset \`unicode-range\` splits means an Uzbek page still downloads only
 * the latin subsets, and the "… Fallback" faces carry the metric overrides that
 * keep the swap from shifting layout.
 *
 * To refresh: temporarily restore next/font/google in src/lib/fonts.ts, run
 * \`pnpm build\`, then \`node scripts/vendor-fonts.mjs\`.
 */
`;

const variables = `
:root {
  --font-inter: 'Inter', 'Inter Fallback';
  --font-poppins: 'Poppins', 'Poppins Fallback';
}
`;

writeFileSync(outCss, `${header}\n${unique.join('\n')}\n${variables}`);

console.log(`${unique.length} @font-face rules -> ${path.relative(root, outCss)}`);
console.log(`${copied.size} font files -> ${path.relative(root, outDir)}`);
console.log(`preloaded subsets: ${preload.join(', ')}`);
