import { L } from './common';

/** [prompt, options, index of the correct option] */
export type SeedQuestion = [string, string[], number];

export const KIDS_QUESTIONS: SeedQuestion[] = [
  ['Hello! What ____ your name?', ['is', 'are', 'am', 'be'], 0],
  ['I ____ seven years old.', ['is', 'am', 'are', 'be'], 1],
  ['This is a cat. ____ is black.', ['He', 'She', 'It', 'They'], 2],
  ['Choose the colour: the sun is ____.', ['yellow', 'purple', 'green', 'grey'], 0],
  ['How many legs has a dog got? It has got ____ legs.', ['two', 'three', 'four', 'five'], 2],
  ['— Good morning!\n— ____', ['Good night!', 'Good morning!', 'Goodbye!', 'Thank you!'], 1],
  ['My mother and father are my ____.', ['friends', 'parents', 'teachers', 'pets'], 1],
  ['We ____ at school now.', ['is', 'am', 'are', 'be'], 2],
  ['Look! The birds ____ in the sky.', ['fly', 'flies', 'flying', 'is fly'], 0],
  ['I have got two ____.', ['foot', 'feet', 'foots', 'feets'], 1],
  ['Where do you sleep? In the ____.', ['kitchen', 'bathroom', 'bedroom', 'garden'], 2],
  ['— How old are you?\n— I ____ nine.', ['have', 'am', 'is', 'do'], 1],
  ['The apple is ____ the table.', ['on', 'at', 'of', 'to'], 0],
  ['She ____ milk every morning.', ['drink', 'drinks', 'drinking', 'is drink'], 1],
  ['Choose the animal: it says "meow".', ['a dog', 'a cow', 'a cat', 'a duck'], 2],
  ['I can ____ a bike.', ['ride', 'rides', 'riding', 'to ride'], 0],
  ['These are my books. They are ____.', ['my', 'mine', 'me', 'I'], 1],
  ['— Whose pencil is this?\n— It is ____ pencil.', ['Toms', "Tom's", 'Tom', 'of Tom'], 1],
  ['There ____ four chairs in the room.', ['is', 'are', 'am', 'be'], 1],
  ['We go to school ____ Monday.', ['in', 'at', 'on', 'of'], 2],
  ['My sister ____ TV now.', ['watch', 'watches', 'is watching', 'watching'], 2],
  ['Winter is ____ than summer.', ['cold', 'colder', 'coldest', 'more cold'], 1],
  ['I like ice cream, ____ I do not like onions.', ['and', 'but', 'or', 'so'], 1],
  [
    '— Can I have some water, please?\n— ____',
    ['Yes, you can.', 'Yes, I do.', 'No, I am not.', 'Yes, it is.'],
    0,
  ],
  ['Yesterday we ____ to the zoo.', ['go', 'goes', 'went', 'going'], 2],
  ['He has got ____ orange juice.', ['a', 'an', 'some', 'many'], 2],
  ['Look at the clock: it is half ____ three.', ['past', 'to', 'at', 'on'], 0],
  ['There are ____ apples in the basket.', ['much', 'many', 'a', 'any'], 1],
  ['She is the ____ girl in the class.', ['tall', 'taller', 'tallest', 'most tall'], 2],
  ['I ____ my homework yesterday evening.', ['do', 'did', 'does', 'doing'], 1],
  ['We must ____ quiet in the library.', ['be', 'are', 'being', 'is'], 0],
  ['— What is the weather like?\n— It ____ raining.', ['is', 'are', 'has', 'does'], 0],
  ['My birthday is ____ May.', ['on', 'at', 'in', 'to'], 2],
  ['He is good ____ football.', ['in', 'at', 'on', 'for'], 1],
  ['They ____ not like fish.', ['does', 'do', 'is', 'are'], 1],
  ['Tomorrow I ____ visit my grandmother.', ['am', 'will', 'was', 'did'], 1],
  [
    'Put the words in order: (bag / is / my / this)',
    ['This is my bag.', 'My bag this is.', 'Is this my bag.', 'This my bag is.'],
    0,
  ],
  ['I have never ____ a lion.', ['see', 'saw', 'seen', 'seeing'], 2],
  ['If it rains, we ____ at home.', ['stay', 'will stay', 'stayed', 'staying'], 1],
  ['The cake ____ by my mother.', ['made', 'was made', 'is make', 'makes'], 1],
  ['She asked me where I ____ from.', ['come', 'came', 'coming', 'comes'], 1],
  ['I am looking forward ____ the holidays.', ['to', 'for', 'at', 'on'], 0],
  ['This is the boy ____ won the competition.', ['which', 'who', 'whose', 'whom'], 1],
  [
    'You ____ eat so many sweets — it is bad for your teeth.',
    ['should not', 'must to', 'do not have', 'are not'],
    0,
  ],
  [
    '— How long have you studied English?\n— ____ two years.',
    ['Since', 'For', 'During', 'From'],
    1,
  ],
];

export const GENERAL_QUESTIONS: SeedQuestion[] = [
  ['Nice to meet you. My name ____ Aziz.', ['am', 'is', 'are', 'be'], 1],
  ['Where ____ you from?', ['is', 'am', 'are', 'do'], 2],
  ['She ____ in a bank.', ['work', 'works', 'working', 'is work'], 1],
  ['They ____ got a new car.', ['has', 'have', 'is', 'are'], 1],
  ['There is ____ milk in the fridge.', ['a', 'an', 'some', 'many'], 2],
  ['I usually get up ____ 7 o’clock.', ['in', 'on', 'at', 'to'], 2],
  [
    'This book is ____ than that one.',
    ['interesting', 'more interesting', 'most interesting', 'interestinger'],
    1,
  ],
  ['— What are you doing?\n— I ____ dinner.', ['cook', 'cooks', 'am cooking', 'cooked'], 2],
  ['We ____ to Samarkand last summer.', ['go', 'went', 'gone', 'going'], 1],
  ['He can ____ three languages.', ['speaks', 'speak', 'speaking', 'to speak'], 1],
  ['How ____ sugar do you take in your tea?', ['many', 'much', 'few', 'lots'], 1],
  ['I am not very good ____ maths.', ['in', 'on', 'at', 'for'], 2],
  ['She has lived here ____ 2015.', ['for', 'since', 'from', 'during'], 1],
  ['If I ____ time, I will call you.', ['have', 'will have', 'had', 'having'], 0],
  ['The film was ____ boring that I fell asleep.', ['such', 'so', 'too', 'very'], 1],
  ['This is the restaurant ____ we met.', ['which', 'where', 'who', 'when'], 1],
  [
    'You ____ smoke here. It is forbidden.',
    ['must not', 'do not have to', 'need not', 'should'],
    0,
  ],
  ['My car ____ last week.', ['stole', 'was stolen', 'is stolen', 'has stole'], 1],
  ['He said he ____ tired.', ['is', 'was', 'has been', 'will be'], 1],
  ['I would rather ____ at home tonight.', ['stay', 'to stay', 'staying', 'stayed'], 0],
  [
    'By the time we arrived, the concert ____.',
    ['started', 'has started', 'had started', 'was starting'],
    2,
  ],
  ['She is used ____ early.', ['to get up', 'to getting up', 'get up', 'getting up'], 1],
  ['Neither of the answers ____ correct.', ['are', 'is', 'were', 'be'], 1],
  ['I wish I ____ how to drive.', ['know', 'knew', 'have known', 'will know'], 1],
  [
    'The report ____ by Friday.',
    ['must finish', 'must be finished', 'must finished', 'must to finish'],
    1,
  ],
  ['He apologised ____ being late.', ['of', 'for', 'about', 'to'], 1],
  ['It is high time we ____ a decision.', ['make', 'made', 'will make', 'making'], 1],
  [
    'Hardly ____ the door when the phone rang.',
    ['I had opened', 'had I opened', 'I opened', 'did I open'],
    1,
  ],
  ['She denied ____ the money.', ['to take', 'taking', 'take', 'taken'], 1],
  ['The more you practise, ____ you become.', ['the better', 'better', 'the best', 'good'], 0],
  ['I look forward to ____ from you.', ['hear', 'hearing', 'heard', 'be heard'], 1],
  [
    'If I had studied harder, I ____ the exam.',
    ['would pass', 'would have passed', 'will pass', 'passed'],
    1,
  ],
  ['He is responsible ____ the marketing department.', ['of', 'to', 'for', 'with'], 2],
  [
    'Not only ____ late, but he also forgot the documents.',
    ['he was', 'was he', 'he is', 'is he'],
    1,
  ],
  ['The meeting was put ____ until next Monday.', ['off', 'on', 'up', 'out'], 0],
  [
    'She speaks English ____ fluently ____ her brother.',
    ['as / as', 'so / as', 'more / than', 'as / than'],
    0,
  ],
  ['I would appreciate it if you ____ me know.', ['let', 'would let', 'will let', 'have let'], 1],
  ['There is no point ____ about it now.', ['to worry', 'worrying', 'worry', 'in worry'], 1],
  ['He came across ____ arrogant during the interview.', ['as', 'like', 'for', 'to'], 0],
  ['The proposal was turned ____ by the board.', ['down', 'off', 'over', 'in'], 0],
  ['Little ____ that she was already famous.', ['I knew', 'did I know', 'I did know', 'knew I'], 1],
  [
    'Under no circumstances ____ the machine unattended.',
    ['you should leave', 'should you leave', 'you leave', 'leave you'],
    1,
  ],
  ['She is entitled ____ a full refund.', ['for', 'to', 'of', 'with'], 1],
  ['The results were, ____ and large, satisfactory.', ['by', 'in', 'at', 'on'], 0],
  [
    'Were it not for your help, the project ____ failed.',
    ['would have', 'will have', 'had', 'would'],
    0,
  ],
];

export const TEST_CATEGORIES = [
  {
    slug: 'level-kids',
    title: L('KIDS', 'KIDS', 'KIDS'),
    subtitle: L(
      '7–12 yoshdagi bolalar uchun daraja aniqlash testi',
      'Тест на определение уровня для детей 7–12 лет',
      'A placement test for children aged 7–12',
    ),
    icon: 'Baby',
    timeLimitSec: 1800,
    shuffle: false,
    allowBack: true,
    requireContact: true,
    order: 1,
    questions: KIDS_QUESTIONS,
    bands: [
      {
        minScore: 0,
        maxScore: 11,
        levelName: 'Starter',
        courseSlug: 'kids-english',
        title: L('Starter darajasi', 'Уровень Starter', 'Starter level'),
        description: L(
          "Alifbo va birinchi so'zlardan boshlaymiz. Kids English 1-daraja guruhi sizga mos.",
          'Начинаем с алфавита и первых слов. Подойдёт группа Kids English 1 уровня.',
          'We start with the alphabet and first words. The Kids English level 1 group is right for you.',
        ),
        order: 1,
      },
      {
        minScore: 12,
        maxScore: 22,
        levelName: 'Beginner',
        courseSlug: 'kids-english',
        title: L('Beginner darajasi', 'Уровень Beginner', 'Beginner level'),
        description: L(
          "Asosiy so'zlarni bilasiz, endi gap tuzishni mashq qilamiz. Kids English 2-daraja.",
          'Вы знаете базовые слова, теперь тренируем построение предложений. Kids English 2 уровень.',
          'You know the basic words; next we practise building sentences. Kids English level 2.',
        ),
        order: 2,
      },
      {
        minScore: 23,
        maxScore: 33,
        levelName: 'Elementary',
        courseSlug: 'kids-english',
        title: L('Elementary darajasi', 'Уровень Elementary', 'Elementary level'),
        description: L(
          "O'tgan zamon va qisqa hikoyalar ustida ishlaymiz. Kids English 3-daraja.",
          'Работаем над прошедшим временем и короткими рассказами. Kids English 3 уровень.',
          'We work on past tenses and short stories. Kids English level 3.',
        ),
        order: 3,
      },
      {
        minScore: 34,
        maxScore: 45,
        levelName: 'Flyers',
        courseSlug: 'kids-english',
        title: L('Flyers darajasi', 'Уровень Flyers', 'Flyers level'),
        description: L(
          "Ajoyib natija! Cambridge YLE imtihoniga tayyorgarlik guruhiga qo'shilishingiz mumkin.",
          'Отличный результат! Можно присоединиться к группе подготовки к Cambridge YLE.',
          'Excellent result! You can join the Cambridge YLE preparation group.',
        ),
        order: 4,
      },
    ],
  },
  {
    slug: 'level-general',
    title: L('GENERAL', 'GENERAL', 'GENERAL'),
    subtitle: L(
      'Kattalar uchun umumiy ingliz tili darajasini aniqlash testi',
      'Тест на определение общего уровня английского для взрослых',
      'A general English placement test for adults',
    ),
    icon: 'Users',
    timeLimitSec: 2400,
    shuffle: false,
    allowBack: true,
    requireContact: true,
    order: 2,
    questions: GENERAL_QUESTIONS,
    bands: [
      {
        minScore: 0,
        maxScore: 9,
        levelName: 'Beginner',
        courseSlug: 'general-english',
        title: L('Beginner (A1)', 'Beginner (A1)', 'Beginner (A1)'),
        description: L(
          'Noldan boshlaymiz — General English Beginner guruhi siz uchun.',
          'Начинаем с нуля — вам подойдёт группа General English Beginner.',
          'We start from zero — the General English Beginner group is for you.',
        ),
        order: 1,
      },
      {
        minScore: 10,
        maxScore: 18,
        levelName: 'Elementary',
        courseSlug: 'general-english',
        title: L('Elementary (A2)', 'Elementary (A2)', 'Elementary (A2)'),
        description: L(
          'Oddiy suhbatni tushunasiz. Elementary guruhida grammatikani mustahkamlaymiz.',
          'Вы понимаете простую речь. В группе Elementary укрепим грамматику.',
          'You follow simple conversation. The Elementary group will consolidate your grammar.',
        ),
        order: 2,
      },
      {
        minScore: 19,
        maxScore: 27,
        levelName: 'Pre-Intermediate',
        courseSlug: 'general-english',
        title: L('Pre-Intermediate (B1)', 'Pre-Intermediate (B1)', 'Pre-Intermediate (B1)'),
        description: L(
          'Kundalik mavzularda gapira olasiz. Endi ravonlik ustida ishlaymiz.',
          'Вы говорите на бытовые темы. Теперь работаем над беглостью.',
          'You can talk about everyday topics. Now we work on fluency.',
        ),
        order: 3,
      },
      {
        minScore: 28,
        maxScore: 36,
        levelName: 'Intermediate',
        courseSlug: 'general-english',
        title: L('Intermediate (B1+)', 'Intermediate (B1+)', 'Intermediate (B1+)'),
        description: L(
          'Yaxshi baza. IELTS ga tayyorgarlikni boshlashingiz mumkin.',
          'Хорошая база. Можно начинать подготовку к IELTS.',
          'A solid base — you are ready to start IELTS preparation.',
        ),
        order: 4,
      },
      {
        minScore: 37,
        maxScore: 45,
        levelName: 'Upper-Intermediate',
        courseSlug: 'ielts',
        title: L('Upper-Intermediate (B2)', 'Upper-Intermediate (B2)', 'Upper-Intermediate (B2)'),
        description: L(
          "Zo'r natija! IELTS 7+ guruhiga to'g'ridan-to'g'ri qo'shilishingiz mumkin.",
          'Отличный результат! Можно сразу в группу IELTS 7+.',
          'Excellent result! You can join the IELTS 7+ group straight away.',
        ),
        order: 5,
      },
    ],
  },
];
